lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - .github/CONTRIBUTING.md
  multiqc_config: false
  actions_ci: false # TODO: remove this with nf-core template version 3.3.0
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Luisa Santus, Jose Espinosa-Carrasco
  description: Pipeline to run and benchmark multiple sequence alignment tools.
  force: false
  is_nfcore: true
  name: multiplesequencealign
  org: nf-core
  outdir: .
  version: 1.1.1dev
