# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "visualization"
description: Generate structure-based visual reports by integrating MSAs, trees, and optional structural data.
keywords:
  - visualization
  - FoldMason
  - structural bioinformatics
  - multiple sequence alignment
  - tree analysis
  - LDDT
  - comparative analysis
components:
  - foldmason/createdb
  - foldmason/msa2lddtreport
input:
  - ch_msa:
      description: Channel containing multiple sequence alignment (MSA) files.
      structure:
        - meta:
            type: map
            description: Metadata map for each MSA dataset.
        - msa:
            type: file
            description: Input MSA file in FASTA or alignment format.
            pattern: "*.{fasta,fa,aln,faa}"
  - ch_trees:
      description: Channel containing phylogenetic tree files corresponding to MSAs.
      structure:
        - meta:
            type: map
            description: Metadata map for each dataset.
        - tree:
            type: file
            description: Input tree file in Newick or similar format.
            pattern: "*.{nwk,tree,txt}"
  - ch_optional_data:
      description: Optional structural data directory.
      structure:
        - meta:
            type: map
            description: Metadata map for each dataset.
        - pdbs_dir:
            type: directory
            description: Input directory containing PDB or predicted structure files.
            pattern: "*/*.pdb"
output:
  - html:
      description: HTML visualization reports generated by FoldMason.
      structure:
        - meta:
            type: map
            description: Metadata map for each dataset.
        - html:
            type: file
            description: Output visualization report in HTML format.
            pattern: "*.html"
  - versions:
      type: file
      description: File containing software version information.
      pattern: "versions.yml"
authors:
  - "@luisasantus"
maintainers:
  - "@luisasantus"
