# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "align"
description: Compute guide trees if required and perform multiple sequence or structure-based alignments. Compute consensus alignments if specified.
keywords:
  - alignment
  - guide tree
  - MSA
  - structure-based alignment
  - sequence-based alignment
  - consensus
components:
  - compute/trees
  - clustalo/align
  - famsa/align
  - foldmason/easymsa
  - kalign/align
  - learnmsa/align
  - mafft/align
  - magus/align
  - mtmalign/align
  - muscle5/super5
  - tcoffee/align
  - tcoffee/regressive
  - tcoffee/consensus
  - upp/align
  - pigz/compress
input:
  - ch_fastas:
      description: Input FASTA sequences for which alignments will be computed.
      structure:
        - meta:
            type: map
            description: Metadata map for each FASTA input.
        - fastas:
            type: file
            description: Input FASTA file(s).
            pattern: "*.{fasta,fa,faa}"
  - ch_tools:
      description: Channel specifying both the guide tree and aligner tools with their respective arguments.
      structure:
        - meta_tree:
            type: map
            description: Metadata specifying guide tree computation tool (e.g. FAMSA, CLUSTALO, MAFFT) and parameters.
        - meta_aligner:
            type: map
            description: Metadata specifying alignment tool (e.g. TCOFFEE, MAFFT, MUSCLE5) and parameters.
  - ch_optional_data:
      description: Optional data for structure-based alignments (e.g., PDB templates or dependencies).
      structure:
        - meta:
            type: map
            description: Metadata map for optional data.
        - files:
            type: file
            description: List of optional structural data files.
            pattern: "*.{pdb}"
  - compress:
      type: boolean
      description: Whether to compress output alignments using Pigz.
output:
  - msa:
      description: Multiple sequence alignments generated by the specified tools.
      structure:
        - meta:
            type: map
            description: Metadata map including aligner and arguments.
        - msa:
            type: file
            description: Output alignment file.
            pattern: "*.{aln,fasta,fas,msa,fa,gz}"
  - trees:
      description: Computed guide trees, used for tree-guided alignments.
      structure:
        - meta:
            type: map
            description: Metadata map including tree computation tool.
        - tree:
            type: file
            description: Guide tree file.
            pattern: "*.{nwk,tree}"
  - versions:
      type: file
      description: File containing software version information for all tools used.
      pattern: "versions.yml"
authors:
  - "@luisasantus"
  - "@joseespinosa"
  - "@mirpedrol"
  - "@lrauschning"
maintainers:
  - "@luisasantus"
  - "@joseespinosa"
